<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="shortcut icon" href="static/img/favicon.ico" type="image/x-icon">
  <link rel="stylesheet" href="static/css/reset.css">
  <link rel="stylesheet" href="static/css/fonts.css">
  <link rel="stylesheet" href="static/css/main.css">
  <link rel="stylesheet" href="static/css/top_bar.css">
  <link rel="stylesheet" href="static/css/nav.css">
  <link rel="stylesheet" href="static/css/post.css">
  <link id="theme" rel="stylesheet" href="static/css/red_theme.css">
  <script src="static/js/main.js"></script>
  <title>JS Forum | <? echo $page->get_title() ?></title>
</head>

<body>

  <!-- Display session variables for errors and successes -->
  <? if (session_status() == PHP_SESSION_NONE) session_start(); ?>
  
  <!-- Error toast -->
  <? if (isset($_SESSION['err']) && $_SESSION['err']) { ?>
    <div class="toast_notification err">
      <img src="static/img/icon/err.svg">
      <?
        echo $_SESSION['err'];
        $_SESSION['err'] = null;
      ?>
    </div>
  <? } ?>

  <!-- Success toast -->
  <? if (isset($_SESSION['success']) && $_SESSION['success']) { ?>
    <div class="toast_notification success">
      <img src="static/img/icon/success.svg" class="colour_by_theme">
      <?
        echo $_SESSION['success'];
        $_SESSION['success'] = null;
      ?>
    </div>
  <? } ?>