<?
$author = $db->get_user_by_id($post['author']);

$is_message = isset($is_message) ? $is_message : null;
$is_full = isset($is_full) ? $is_full : null;
if (!$is_message) $category = $db->get_category($post['category']);
?>

<div class="post_item">
    <div class="post_item__details">
        <a href="/profile.php?u=<? echo $author['id'] ?>" class="post_item__profile_img"><? echo $db->get_user_img('profile_img', $author['id']) ?></a>
    </div>
    <div class="post_item__content">
        <div class="post_item__header">
            <div>
                <div class="post_item__title">
                    <a class="h4" <? if (!$is_message) { ?>href="/post.php?p=<? echo $post['id'] ?>"<? } ?>><? echo $post['title'] ?></a>
                    <? if (!$is_message) { ?>
                        <a href="?c=<? echo $category['id'] ?>" class="post_item__category"><? echo $category['name'] ?></a>
                    <? } ?>
                </div>
                <a class="post_item__author" href="/profile.php?u=<? echo $author['id'] ?>"><? echo $author['username'] ?></a>
            </div>
            <?
            $phpdate = strtotime($post['creation_date']);
            $mysqldate = date('d M Y', $phpdate);
            ?>
            <p class="post_item__date"><? echo $mysqldate ?></p>
        </div>
        <a <? if (!$is_message) { ?>href="/post.php?p=<? echo $post['id'] ?>"<? } ?> class="post_item__body <? if (!$is_full) echo 'trunc' ?>"><? echo $post['body'] ?></a>
    </div>
</div>