<?
require 'view/template/header.phtml';
require 'view/template/top_bar.phtml';
require 'view/template/nav.phtml';
?>

<main>
  <div class="page">
    <div class="page_header">
      <div class="postfix_icon">
        <h2>Chat</h2>
        <img src="static/img/nav/chat.svg">
      </div>
    </div>

    <div class="chat_wrapper">
      <div class="chat_people">
        <div class="chat_people_search">
          <form action="/controller/search.php" method="POST">
            <input type="text" name="chat_people_search" placeholder="Search..." required>
            <button name="chat_people_search_submit" type="submit">
              <img src="static/img/icon/search.svg" alt="Logo">
            </button>
          </form>
        </div>
        <ul id="chat_people_list">
          <?
            $chats = $db->get_chats($_SESSION['uid']);
            while ($post = $db->fetch_from($chats)) {
              $is_message = true;
              $post['title'] = '';
              $recipient = $post['author'];
              if (isset($_GET['c']) && $_GET['c'] == $recipient) {
                echo "<li data-recipient='$recipient' class='active'>";
              } else {
                echo "<li data-recipient='$recipient'>";
              }
              require 'view/template/post.phtml';
              echo '</li>';
            }
          ?>
        </ul>
      </div>

      <div class="chat_main">
        
        <div class="chat_main__messages">
          <?
            if (isset($_GET['c'])) {
              $messages = $db->get_chat($_SESSION['uid'], $_GET['c']);
              while ($message = $db->fetch_from($messages)) {
                require 'view/template/bubble.phtml';
              }
            }
          ?>
        </div>
          
        <div class="chat_main_input">
          <form>
            <input type="text" name="chat_main_input" placeholder="Send a message..." required>
            <button name="chat_main_input_submit" type="submit">
              <img src="static/img/icon/compose.svg" alt="Logo">
            </button>
          </form>
        </div>
      </div>
    </div>

  </div>
</main>

<script src="static/js/chat.js"></script>

<? require 'view/template/footer.phtml' ?>