<?
require 'view/template/header.phtml';
require 'view/template/top_bar.phtml';
require 'view/template/nav.phtml';
?>

<main>

  <div class="page">
    <div class="page_header">
      <div class="postfix_icon">
        <h2>Help</h2>
        <img src="static/img/nav/help.svg">
      </div>
    </div>
    <h4>Help page and FAQ coming soon</h4>
  </div>
  
</main>

<? require 'view/template/footer.phtml' ?>