<?
require 'view/template/header.phtml';
require 'view/template/top_bar.phtml';
require 'view/template/nav.phtml';

$categories = $db->get_categories();
$c = get_c(); // Categories
$p = get_p(); // Page number
$l = get_l(); // Page length
$s = $_GET['s']; // Search query
?>

<main>

  <!-- Posts list -->
  <div class="page_split_left">
    <div class="post_list">

      <? $c_string = isset($_GET['c']) ? $_GET['c'] : ''; ?>
      <a href="<? echo "?c=$c_string&p=".($p-1>0?$p-1:1)."&l=$l&s=$s" ?>" class="button style3">🡰</a>
      <a href="<? echo "?c=$c_string&p=".($p+1)."&l=$l&s=$s" ?>" class="button style3">🡲</a>

    </div>
  </div>

  <!-- Filter form -->
  <div class="page_split_right">
    <h2>Filter</h2>
    <form action="controller/filter_search.php" method="POST">
      <div class="checkbox_wrapper">
        <? while ($category = $db->fetch_from($categories)) { ?>
          <div class="checkbox">
            <input type="checkbox" <? if (!$c || in_array($category['id'], $c)) echo 'checked' ?> name="<? echo $category['id'] ?>">
            <span><? echo $category['name'] ?></span>
          </div>
        <? } ?>
      </div>
      <div>
        <input name="page_num" type="number" min="1" class="style1" value="<? echo $p ?>">
        <label>Jump to page</label>
      </div>
      <div>
        <input name="page_len" type="number" min="1" class="style1" value="<? echo $l ?>">
        <label>Results per page</label>
      </div>
      <input type="hidden" name="query" value="<? echo $s ?>">
      <button type="submit" class="style3" name="filter_submit">Submit</button>
    </form> 
  </div>

</main>

<script src="static/js/search.js"></script>

<? require 'view/template/footer.phtml' ?>