<?
require 'view/template/header.phtml';
require 'view/template/top_bar.phtml';
require 'view/template/nav.phtml';
?>

<main>
  <div class="page">
    <div class="page_header">
      <div class="postfix_icon">
        <h2>Settings</h2>
        <img src="static/img/nav/settings.svg">
      </div>
    </div>
    <h3>Theme</h3>
    <div id="colour_palette" class="colour_palette">
      <ul>
        <li onclick="setColour('default')" data-colour="default"></li>
        <li onclick="setColour('green')" data-colour="green"></li>
        <li onclick="setColour('red')" data-colour="red"></li>
      </ul>
    </div>
  </div>
</main>

<script>
  function setColour(colour) {
    localStorage.setItem("theme", colour)
    $("theme").href = `static/css/${colour}_theme.css`;
  }
</script>

<? require 'view/template/footer.phtml' ?>