<?
require 'view/template/header.phtml';
require 'view/template/top_bar.phtml';
require 'view/template/nav.phtml';

$p = get_p(); // Page number
$l = get_l(); // Page length
?>

<main>

  <!-- Posts list -->
  <div class="page_split_left">
    <div class="page_header">
      <div class="postfix_icon">
        <h2>Watch list</h2>
        <img src="static/img/nav/watch_list.svg">
      </div>
      <div>
        <a href="/controller/watch_list_remove.php?n=*" class="button style3 warn">Remove all</a>
      </div>
    </div>

    <div class="post_list">
      <?
        $watch_list = $db->get_watch_list($p, $l, $_SESSION['uid']);
        if ($watch_list->num_rows > 0) {
          while ($post = $db->fetch_from($watch_list)) {
            require 'view/template/post.phtml';
          }
        } else {
          echo 'No posts to show';
          echo '<br><br>';
        }
      ?>

      <br><br>
      <a href="<? echo "?p=".($p-1>0?$p-1:1)."&l=$l" ?>" class="button style3">🡰</a>
      <a href="<? echo "?p=".($p+1)."&l=$l" ?>" class="button style3">🡲</a>
    </div>
  </div>

  <!-- Filter form -->
  <div class="page_split_right">
    <h2>Filter</h2>
    <form action="controller/filter_watch_list.php" method="POST">
      <div>
        <input name="page_num" type="number" min="1" class="style1" value="<? echo $p ?>">
        <label>Jump to page</label>
      </div>
      <div>
        <input name="page_len" type="number" min="1" class="style1" value="<? echo $l ?>">
        <label>Results per page</label>
      </div>
      <button type="submit" class="style3" name="filter_submit">Submit</button>
    </form>
  </div>

</main>

<? require 'view/template/footer.phtml' ?>